name: tests

on: [push]

jobs:
  test:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4
      - name: Set up uv (${{ matrix.python-version }})
        uses: astral-sh/setup-uv@v5
      - name: Install tox
        run: uv tool install --python-preference only-managed tox --with tox-uv
      - name: Test with tox
        run: tox run
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.python-version }}
